import { useState } from 'react';
import { Wand2, Plus, Music, Zap, Sparkles } from 'lucide-react';
import { generateMoodPlaylist, generateActivityPlaylist, createPlaylist } from '../../api/playlists';
import { Button } from '../../components/ui/Button';
import toast from 'react-hot-toast';

const MoodGenerator = () => {
  const [selectedMood, setSelectedMood] = useState(null);
  const [selectedActivity, setSelectedActivity] = useState(null);
  const [customPrompt, setCustomPrompt] = useState('');
  const [generating, setGenerating] = useState(false);
  const [generatedTracks, setGeneratedTracks] = useState(null);
  const [playlistName, setPlaylistName] = useState('');
  const [saving, setSaving] = useState(false);

  const moods = [
    { name: 'Happy', emoji: '😄', color: 'from-yellow-400 to-orange-500', targetMood: 'Happy' },
    { name: 'Calm', emoji: '😌', color: 'from-blue-400 to-cyan-500', targetMood: 'Calm' },
    { name: 'Sad', emoji: '😢', color: 'from-gray-400 to-blue-500', targetMood: 'Sad' },
    { name: 'Energetic', emoji: '⚡', color: 'from-red-400 to-pink-500', targetMood: 'Energetic' },
    { name: 'Romantic', emoji: '❤️', color: 'from-pink-400 to-rose-500', targetMood: 'Romantic' },
    { name: 'Focused', emoji: '🎯', color: 'from-purple-400 to-indigo-500', targetMood: 'Focus' },
  ];

  const activities = [
    { name: 'Study', emoji: '📚', activity: 'study' },
    { name: 'Workout', emoji: '💪', activity: 'workout' },
    { name: 'Party', emoji: '🎉', activity: 'party' },
    { name: 'Sleep', emoji: '😴', activity: 'sleep' },
    { name: 'Work', emoji: '💼', activity: 'work' },
    { name: 'Meditation', emoji: '🧘', activity: 'meditation' },
  ];

  const handleGenerateMood = async (mood) => {
    setSelectedMood(mood);
    setSelectedActivity(null);
    setGenerating(true);
    setGeneratedTracks(null);

    try {
      console.log('🎨 Generating mood playlist:', mood.name);
      const result = await generateMoodPlaylist(mood.targetMood, 30);
      setGeneratedTracks(result);
      setPlaylistName(`${mood.name} Vibes - ${new Date().toLocaleDateString()}`);
      toast.success(`Generated ${result.total || result.tracks?.length || 0} tracks!`);
    } catch (error) {
      console.error('Failed to generate mood playlist:', error);
      toast.error(error.response?.data?.message || 'Failed to generate playlist');
    } finally {
      setGenerating(false);
    }
  };

  const handleGenerateActivity = async (activity) => {
    setSelectedActivity(activity);
    setSelectedMood(null);
    setGenerating(true);
    setGeneratedTracks(null);

    try {
      console.log('🏃 Generating activity playlist:', activity.name);
      const result = await generateActivityPlaylist(activity.activity, 30);
      setGeneratedTracks(result);
      setPlaylistName(`${activity.name} Mix - ${new Date().toLocaleDateString()}`);
      toast.success(`Generated ${result.total || result.tracks?.length || 0} tracks!`);
    } catch (error) {
      console.error('Failed to generate activity playlist:', error);
      toast.error(error.response?.data?.message || 'Failed to generate playlist');
    } finally {
      setGenerating(false);
    }
  };

  const handleSaveToSpotify = async () => {
    if (!generatedTracks || !playlistName) {
      toast.error('Please generate a playlist first');
      return;
    }

    setSaving(true);
    try {
      const tracks = generatedTracks.tracks || [];
      const trackUris = tracks.map(t => `spotify:track:${t.id}`);
      
      const result = await createPlaylist(
        playlistName,
        trackUris,
        `Generated by MoodiQ-AI on ${new Date().toLocaleDateString()}`,
        true
      );

      toast.success('Playlist saved to Spotify!');
      window.open(result.url, '_blank');
    } catch (error) {
      console.error('Failed to save playlist:', error);
      toast.error('Failed to save playlist to Spotify');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2 flex items-center gap-3">
          <Wand2 className="w-8 h-8 text-purple-600" />
          Mood Generator
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          Create personalized playlists based on your mood or activity
        </p>
      </div>

      {/* Mood Selection */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-indigo-600" />
          Choose Your Mood
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {moods.map((mood, index) => (
            <button
              key={index}
              onClick={() => handleGenerateMood(mood)}
              disabled={generating}
              className={`bg-gradient-to-br ${mood.color} text-white rounded-xl p-6 text-center hover:scale-105 transition-transform shadow-lg disabled:opacity-50 disabled:cursor-not-allowed ${
                selectedMood?.name === mood.name ? 'ring-4 ring-white' : ''
              }`}
            >
              <div className="text-4xl mb-2">{mood.emoji}</div>
              <h3 className="text-lg font-bold">{mood.name}</h3>
            </button>
          ))}
        </div>
      </div>

      {/* Activity Selection */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <Zap className="w-6 h-6 text-green-600" />
          Choose Your Activity
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {activities.map((activity, index) => (
            <button
              key={index}
              onClick={() => handleGenerateActivity(activity)}
              disabled={generating}
              className={`bg-gradient-to-br from-green-500 to-emerald-600 text-white rounded-xl p-6 text-center hover:scale-105 transition-transform shadow-lg disabled:opacity-50 disabled:cursor-not-allowed ${
                selectedActivity?.name === activity.name ? 'ring-4 ring-white' : ''
              }`}
            >
              <div className="text-4xl mb-2">{activity.emoji}</div>
              <h3 className="text-lg font-bold">{activity.name}</h3>
            </button>
          ))}
        </div>
      </div>

      {/* Custom Prompt (Future Enhancement) */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
        <h2 className="text-xl font-bold mb-4">Custom Mood (Coming Soon)</h2>
        <p className="text-gray-600 dark:text-gray-400 mb-4">
          Describe the mood you want and let AI create a perfect playlist
        </p>
        <textarea
          placeholder="E.g., 'Upbeat music for a road trip' or 'Cozy evening vibes'"
          className="w-full p-4 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 mb-4"
          rows={3}
          value={customPrompt}
          onChange={(e) => setCustomPrompt(e.target.value)}
          disabled
        />
        <Button disabled className="opacity-50 cursor-not-allowed">
          <Wand2 className="w-5 h-5 mr-2" />
          Generate Custom Playlist (Coming Soon)
        </Button>
      </div>

      {/* Generation Progress */}
      {generating && (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-12 text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-indigo-600 mx-auto mb-4"></div>
          <p className="text-xl font-semibold text-gray-700 dark:text-gray-300">
            Generating your perfect playlist...
          </p>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
            AI is analyzing millions of tracks to find your vibe
          </p>
        </div>
      )}

      {/* Generated Playlist */}
      {generatedTracks && !generating && (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 space-y-6">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h2 className="text-2xl font-bold mb-2">Generated Playlist</h2>
              <p className="text-gray-600 dark:text-gray-400">
                {generatedTracks.total || generatedTracks.tracks?.length || 0} tracks generated
              </p>
            </div>
            <div className="flex flex-col gap-3 w-full md:w-auto">
              <input
                type="text"
                value={playlistName}
                onChange={(e) => setPlaylistName(e.target.value)}
                className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700"
                placeholder="Enter playlist name"
              />
              <Button 
                onClick={handleSaveToSpotify} 
                isLoading={saving}
                className="w-full"
              >
                <Plus className="w-5 h-5 mr-2" />
                Save to Spotify
              </Button>
            </div>
          </div>

          {/* Track List */}
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {generatedTracks.tracks?.map((track, index) => (
              <div
                key={track.id || index}
                className="flex items-center gap-4 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
              >
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-100 dark:bg-indigo-900 flex items-center justify-center font-semibold text-indigo-600 dark:text-indigo-300 text-sm">
                  {index + 1}
                </div>

                {track.album?.images?.[0]?.url && (
                  <img
                    src={track.album.images[0].url}
                    alt={track.album.name}
                    className="w-12 h-12 rounded"
                  />
                )}

                <div className="flex-1 min-w-0">
                  <p className="font-semibold truncate">{track.name}</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400 truncate">
                    {track.artists?.map(a => a.name).join(', ')}
                  </p>
                </div>

                {track.preview_url && (
                  <a
                    href={track.preview_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-shrink-0 px-3 py-1 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 rounded-full text-xs font-medium hover:bg-green-200 dark:hover:bg-green-800 transition-colors"
                  >
                    Preview
                  </a>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Info Box */}
      {!generatedTracks && !generating && (
        <div className="bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 rounded-xl p-8 text-center">
          <Music className="w-16 h-16 mx-auto mb-4 text-indigo-600 dark:text-indigo-400" />
          <h3 className="text-xl font-bold mb-2">AI-Powered Playlist Generation</h3>
          <p className="text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
            Select a mood or activity above to generate a personalized playlist. Our AI analyzes
            millions of tracks to find the perfect songs that match your vibe.
          </p>
        </div>
      )}
    </div>
  );
};

export default MoodGenerator;